stages:
  - prod

variables:
  PORT: 4001
  BASE_PATH: "/home/telegram/telegram-mtproto-server"

deploy_prod:
  stage: prod
  tags: ["telegram"]  
  script:
    - sudo systemctl stop mtproxyserver.service
    - sudo rm -rf $BASE_PATH/*
    - mkdir -p $BASE_PATH
    - date > $BASE_PATH/date.txt
    - sudo cp -a ./* $BASE_PATH/
    - printf "%s" "${env}" > .env
    - sudo cp .env $BASE_PATH/.env
    - python -m venv $BASE_PATH/venv
    - source $BASE_PATH/venv/bin/activate
    - pip install -r $BASE_PATH/requirements.txt
    - sudo systemctl start mtproxyserver.service
    - sudo systemctl status mtproxyserver.service
  only:
    - main
