# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git remote add github https://github.com/Ilia-Abolhasani/telegram-mtproto-server.git
    git fetch github
    git checkout -B github-main github/main
    git merge main
    git push origin github-main:main
  displayName: 'Sync with GitHub'

