name: Sync with Azure Repos

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up credentials
      run: |
        git remote add azure ${{ secrets.AZURE_REPO_URL }}
        git config azure.password ${{ secrets.AZURE_REPO_PASSWORD }}
        
        git fetch azure
        git checkout -B azure-master azure/master
        git merge master
        git push azure azure-master:master
